version: "3.8"

services:
  main.py:
    build:
      context: ./   
      dockerfile: app1dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db

  client_app.py:
    build:
      context: ./   
      dockerfile: app2dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - main.py

  db:
    image: "alpine"  
    command: sh -c "while sleep 3600; do :; done"  
    volumes:
      - ./uuid.db:/app/uuid.db  
